name: perovskite
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - openpyxl=3.0.10
  - scikit-learn=1.0.2
  - gpy=1.10.0
  - pydoe=0.3.8
  - ipykernel=6.9.1
  - pandas=1.4.2
  - seaborn=0.11.1
  - pip=22.1
  - pip:
    - emukit==0.4.10
